name: Destroy Cluster

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}      
      ### Configure DO Credentials
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DO_TOKEN }}
          
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy --auto-approve