name: 00-Deploy Cluster

on:
  workflow_dispatch:
  
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ### Configure DO Credentials
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Plan
        id: plan
        run: |
          terraform init -input=false
          terraform plan -var "do_token=${{ secrets.DO_TOKEN }}" -out plan_cache.json -lock=false
          terraform apply -auto-approve plan_cache.json
          
      - name: Terraform apply
        run: terraform apply -auto-approve plan_cache.json -lock=false
        
      - name: Save Terraform state to cache 
        uses: actions/cache@v2
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Kubeconf artefact
        uses: actions/upload-artifact@v2
        with:
          name: kubeconf
          path: |
            kube/*
          retention-days: 1
